### ISSUE TITLE
modules

### ISSUE THREAD

**Issue by jacobwilliams** [Luthaf/linter-gfortran#1]
I can't seem to get it to work with module files.  Even a simple one:

```fortran
module test

end module test
```

The error is `Can't open the module file 'test.mod0' for writing at (1): Permission denied at line 3 col 15`.

**Comment by Luthaf** [comment]
I think the code should set the `-J` and `-I` options of gfortran to point to some writeable directory to fix that.

**Comment by Luthaf** [comment]
This should work now.
