### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by AndreHorst** [Luthaf/linter-gfortran#5]
My project uses cmake to include some libaries. By using "USE library", linter says it can't open 'library'. This is, because it's linked via cmake. If there is a way to consider this, I would be a very happy man!

**Comment by Luthaf** [comment]
I think this is doable by providing a configuration option for the module path (`-J`) instead of using the temporary compilation directory.

I don't have a lot of time right now, do you think you can try to implement this and open a PR?

**Comment by AndreHorst** [comment]
I just checked the settings of the plugin! U can set the folder where the mod files are with the gfortran flags! Thanks for that hint Luthaf!
 
I did this with my 'include' folder which is always above my 'src' folder and it looks like this:
![image](https://cloud.githubusercontent.com/assets/25814609/23021582/edce0614-f44c-11e6-9e44-083d4529ecba.png)
Works like a charm! :-)

**Comment by Luthaf** [comment]
OK, great! I though it would fail when giving the -J option twice. Having a separated setting would still be nice, it feels like the current way of doing it is a hack.
